server:
  port: 3000
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/sims
    username: root
    password: passwd240209
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  main:
    web-application-type: servlet
application:
  api:
    ver: "api/v1"
  security:
    jwt:
      secret-key: ad7205a6abfe94462841119255593a6c595e8d477d152875a4db3c4b2d1416d3
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
